/**
 * LLM Port Interface
 * Supported provider identifiers
 * 'fake' just for tests, rest are real APIs
 */

export type ProviderId = 'anthropic' | 'gemini' | 'openai' | 'fake';

/**
 * ContentBlock: a fragment of content from a message
 * 
 * Why?:
 * - An assistant message con contain TEXT + TOOL CALLS mixed
 * - A message from user can contain TEXT + TOOL RESULTS
 * - Providers manage different content types
 * - Canonicalize everything as an arry of blocks to unify
 */

export type ContentBlock = 
    | { kind: 'text', text: string }
    | {
        kind: 'tool_call';  
        callId: string;    //Unique ID for the tool call
        toolName: string;  // Tool name
        input: unknown;    //Already parsed arguments (JSON object)
      }
    | {
        kind: 'tool_result';
        callId: string;    //Must match with callId in tool_call
        toolName: string;  //Tool name for context
        output: unknown;   // Result from executing the tool
        isError: boolean;  //True if the tool call failed (validation, internal error, etc.)
      }
    | {
        kind: 'opaque';
        provider: ProviderId;  //Where the blob comes from
        payload: unknown;      //Content not modified (thinking blocks, reasoning, etc.)
      }

/**
 * CanonicalMessage: A message as internal format
 * 
 * Why just 'user' and 'assistant'?:
 * - OpenAI has roles: user, assistant, system, tool
 * - Anthropic has roles: user, assistant, (system apart, tool_resut inside the user)
 * - Gemini has roles: user, model, function
 */
export interface CanonicalMessage {
    role: 'user' | 'assistant';
    blocks: ContentBlock[];
}

/**
 * ToolSpec: Definition of a tool which the LLM model can call
 * 
 * This derives on Zod schemas (src/tools/*.ts) using zodToJsonSchema
 */

export interface ToolSpec {
    name: string;
    description: string;
    inputSchema: Record<string, unknown>;  //JSON Schema (OpenAPI 3.0 compatible)
}


/**
 * CompletionRequest: Everything sent to the provider to ask for next turn
 */
export interface CompletionRequest {
    system: string;               //System prompt (current date, rules, etc.)
    messages: CanonicalMessage[]; //Conversation history
    tools: ToolSpec[];            //Available tools
    maxOutputTokens: number;      //Output tokens limit
    temperature?: number;         //0-1, controls randomness (0 = deterministic)
    toolChoice?: 'auto' | 'required' | 'none'; //Force tools usage
}

/**
 * StopReason: Why generation stopped
 * 
 * This helps to decide what to do next:
 * - 'tool_call' -> exeute tools and go back to llm
 * - 'end_turn' -> return text to user
 * - 'max_tokens' -> incomplete message, could expand (not implemented yet)
 * - 'content_filtered' -> the model rejected generation (safety), handoff to human
 */
export type StopReason = 
    | 'tool_call'
    | 'end_turn'
    | 'max_tokens'
    | 'content_filtered'
    | 'other';


/**
 * CompletionResponse: what is received from the provider
 */
export interface CompletionResponse {
    message: CanonicalMessage[];    //Message generated by LLM
    stopReason: StopReason;         //Why generation stopped
    usage: {
        inputTokens: number;        //Tokens used from input (billing)
        outputTokens: number;       //Tokens generated (billing)
    };
}


/**
 * LlmProvider: interfaced used by all adapters
 * 
 * An 'adapter' is a module that knows how to talk with a provider API
 * (Anthropic, Gemini, OpenAI, etc.) and translates between the native format and 
 * our canonical format
 * 
 * It only talks with this interface, never directly with the provider API.
 */
export interface LlmProvider {
    readonly id: ProviderId;

    /**
     * Generate the next turn of the assistant
     * 
     * @param req - Canonical request
     * @param signal - AbortSignal used to cancel the petition if the user disconnects
     * @returns Canonical response
     * @throws If network error, rate limit, invalid API key, etc
     */
    complete(req: CompletionRequest, signal: AbortSignal): Promise<CompletionResponse>;
}